### PR TITLE
FreeBSD/FreeBSD GSSAPI Fixes

### PR DESCRIPTION
**Pull request by zi0r**
- Improve GSSAPI handling under FreeBSD
- Use ifr->ifr_addr instead of ifr->ifr_ifru under FreeBSD

### CODE REVIEW

**Comment by zi0r** [comment]
Note: configure.ac should be updated to `#include <stdio.h>` for any of the GSSAPI-related configure tests.

**Comment by conserver** [comment]
Either of you know the right incantation (or perhaps packages needed) on the cirrus-based freebsd image to get a test build with GSSAPI working?  I tried a quick `configure --with-gssapi`, but it failed to find what it needed and my knowledge of this world is severely lacking, so figured I'd ask.   Thanks!

**Comment by zi0r** [comment]
You would want the port, with the GSSAPI option enabled: [https://www.freshports.org/comms/conserver-com/](https://www.freshports.org/comms/conserver-com/)

> To install the port: cd /usr/ports/comms/conserver-com/ && make install clean

**Comment by conserver** [comment]
Ah...you’re earlier comment about using `stdio.h` did the trick. I shoulda paid a bit more attention.

**Pull request merged**
